services:
  rkllm_server:
    image: thanhtantran/rkllm-gradio:0.1
    container_name: rkllm_chat
    restart: unless-stopped
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - ./models:/app/models  # model mount
      - ./lib:/app/lib # lib mount
    ports:
      - "8080:8080" # 
